
spring.application.name=Film-Datenbank mit GraphQL

# Endung .graphql auch unterstützen, damit VSC-Plugins die Datei erkennen
spring.graphql.schema.file-extensions=.graphql,.graphqls,.gqls

# GraphiQL aktivieren
spring.graphql.graphiql.enabled=true


# Datenbank-Konfiguration für H2
# AUTO_SERVER reduziert Datei-Lock-Probleme, wenn mehrere Prozesse auf dieselbe DB zugreifen.
spring.datasource.url=jdbc:h2:file:./db/filme
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=d4tenb4nk
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# H2-Webkonsole aktivieren
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console