CREATE TABLE IF NOT EXISTS filme (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titel VARCHAR(255) NOT NULL,
    genre VARCHAR(64) NOT NULL,
    erscheinungsjahr INTEGER NOT NULL,
    bewertung REAL,
    regisseur VARCHAR(255),
    verfuegbar BOOLEAN NOT NULL
);
